/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class phoenix3D_nativeIntergration_nativeObjects_NativeWindow */

#ifndef _Included_phoenix3D_nativeIntergration_nativeObjects_NativeWindow
#define _Included_phoenix3D_nativeIntergration_nativeObjects_NativeWindow
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    nativeLinkAssertion
	 * Signature: ()Z
	 */
	JNIEXPORT jboolean JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_nativeLinkAssertion
	(JNIEnv*, jobject);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    createWindow
	 * Signature: (IIIILjava/lang/String;)J
	 */
	JNIEXPORT jlong JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_createWindow
	(JNIEnv*, jobject, jint, jint, jint, jint, jstring);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    openWindow
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_openWindow
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    closeWindow
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_closeWindow
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    transformWindow
	 * Signature: (JIIIIZ)V
	 */
	JNIEXPORT void JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_transformWindow
	(JNIEnv*, jobject, jlong, jint, jint, jint, jint, jboolean);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    setWindowTitle
	 * Signature: (JLjava/lang/String;)V
	 */
	JNIEXPORT void JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_setWindowTitle
	(JNIEnv*, jobject, jlong, jstring);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    getWindowWidth
	 * Signature: (J)I
	 */
	JNIEXPORT jint JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_getWindowWidth
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    getWindowHeight
	 * Signature: (J)I
	 */
	JNIEXPORT jint JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_getWindowHeight
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    getWindowX
	 * Signature: (J)I
	 */
	JNIEXPORT jint JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_getWindowX
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    getWindowY
	 * Signature: (J)I
	 */
	JNIEXPORT jint JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_getWindowY
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    bringWindowToTop
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_bringWindowToTop
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    minimiseWindow
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_minimiseWindow
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    isWindowMinimised
	 * Signature: (J)Z
	 */
	JNIEXPORT jboolean JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_isWindowMinimised
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    maximiseWindow
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_maximiseWindow
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    isWindowMaximised
	 * Signature: (J)Z
	 */
	JNIEXPORT jboolean JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_isWindowMaximised
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    restoreWindow
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_restoreWindow
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    showWindow
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_showWindow
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    hideWindow
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_hideWindow
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    isWindowVisible
	 * Signature: (J)Z
	 */
	JNIEXPORT jboolean JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_isWindowVisible
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    showOwnedPopups
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_showOwnedPopups
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    hideOwnedPopups
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_hideOwnedPopups
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    setActiveWindow
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_setActiveWindow
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    getActiveWindow
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_getActiveWindow
	(JNIEnv*, jobject);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    enableWindow
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_enableWindow
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    disableWindow
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_disableWindow
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     phoenix3D_nativeIntergration_nativeObjects_NativeWindow
	 * Method:    isWindowEnabled
	 * Signature: (J)Z
	 */
	JNIEXPORT jboolean JNICALL Java_phoenix3D_nativeIntergration_nativeObjects_NativeWindow_isWindowEnabled
	(JNIEnv*, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
